### ISSUE TITLE
Road to 0.20: Tauri and everything else

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#751]
Let me keep track of what's working and what's yet to be fixed using the `tauri` branch. Non-exhaustive.

- [x] Database setup **(breaking change)**
- [x] Config setup **(breaking change)**
- [x] Track import
- [x] Loading UI
  - [ ] Fix all TS issues
- [x] Header
  - [x] macOS: overlayed window controls
  - [x] Player controls
  - [x] Search
    - [x] Fix select on focus
  - [x] Hover on progress border moves the tooltip to the wrong location
- [x] Footer
  - [x] Progress tracking
- [x] Library
  - [x] Playback
    - [ ] start button with no queue does not work anymore
  - [x] Context Menu
  - [x] Delete tracks
  - [ ] Drop files on the window to import them
    - [ ] Windows, can it work? https://github.com/tauri-apps/wry/issues/904
  - [x] No way to "show in file manager" https://github.com/tauri-apps/plugins-workspace/issues/999
- [ ] Playlists
  - [ ] Auto-import m3u
  - [ ] Export to m3u
  - [ ] Drag-and-Drop effect is cut when "below"
  - [x] CRUD
    - [x] Create
    - [x] Edit
    - [x] Delete
    - [x] Reorder
      - [x] Fix `get_multiple` not returning docs in the right order
  - [x] Playback
- [x] Covers
  - [x] ID3 -> Base 64
  - [x] Scan folder for `cover.jpg`, etc
- [ ] Settings / Integrations
  - [ ] Theme selection
  - [ ] `__system`  theme
  - [ ] Audio output selection
    - [ ] What of macOS? seems impossible https://bugs.webkit.org/show_bug.cgi?id=216641
  - [x] Single instance
  - [x] macOS close/activate without destroying the window https://github.com/tauri-apps/tauri/issues/3084
  - [x] Devtools
  - [x] Dialogs
  - [ ] Dock actions (macOS)
  - [x] Menu
    - [ ] Menu Events
    - [ ] Show/Hide menu on Alt in Windows/Linux
  - [ ] Dynamically set window theme at runtime https://github.com/tauri-apps/tauri/issues/5279
  - [x] Sleep Blocker
  - [ ] Thumbbar
  - [x] Window Position
  - [x] Sleepblocker
  - [x] Track change notifications
- [ ] CI
  - [ ] Pass QA
  - [ ] Build binaries
    - [ ] Windows
    - [x] macOS
    - [ ] Linux
- [ ] Misc
  - [ ] Listen events on macOS is broken? https://github.com/tauri-apps/tauri/issues/9052
  - [ ] TS exports to a single file https://github.com/Aleph-Alpha/ts-rs/issues/59
  - [ ] `Unhandled Promise Rejection: QuotaExceededError: The quota has been exceeded.` on webkit
- [ ] Accessibility 
  - [ ] Bring back focus ring
- [ ] Final test
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux

## Screenshots

![Screenshot 2024-03-05 223247](https://github.com/martpie/museeks/assets/1311607/6ae5be9c-3751-40e1-b05b-8d9988aceafc)

![Screenshot 2024-03-12 at 16 31 17](https://github.com/martpie/museeks/assets/1311607/fe147bba-495e-4d26-93d1-970e337c8d07)
